# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-addeddate'], 'verbose_name': 'people'},
        ),
        migrations.AlterField(
            model_name='person',
            name='shortname',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('firstname', 'lastname')]),
        ),
    ]
