# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160825_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tasks',
            field=models.ManyToManyField(to='app.Task'),
        ),
    ]
