# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-addeddate'], 'verbose_name_plural': 'people'},
        ),
    ]
