# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160825_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='capability',
            field=models.CharField(default='Wintel', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='manager',
            field=models.CharField(default='Leon Skillings', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='personalemail',
            field=models.EmailField(default='sample@email.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='personalphone',
            field=models.CharField(default=8889990000, max_length=12),
            preserve_default=False,
        ),
    ]
