# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160825_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='person',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='person',
            name='personalemail',
        ),
        migrations.RemoveField(
            model_name='person',
            name='personalphone',
        ),
        migrations.AddField(
            model_name='assignment',
            name='shortname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task'),
        ),
    ]
