# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160903_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AddField(
            model_name='assignment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
