# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_person_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employtype',
            field=models.CharField(choices=[('Contractor', 'Contractor'), ('Employee', 'Employee')], default='Contractor', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='personalemail',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='workemail',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
