# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_person_workemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='capability',
            field=models.CharField(choices=[('ADS', 'ADS'), ('CDS', 'CDS'), ('VDS', 'VDS'), ('PCC', 'PCC'), ('VM', 'Virtualization'), ('AD', 'Active Directory'), ('BAC', 'Backup'), ('STO', 'Storage'), ('UNX', 'UNIX'), ('WIN', 'Wintel')], default='Wintel', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='csctransfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='kite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='personalphone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=-7666, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='team',
            field=models.CharField(choices=[('iACTION', 'iACTION'), ('iBUILD', 'iBUILD'), ('iENHANCE', 'iENHANCE'), ('iSOLVE', 'iSOLVE')], default='iBUILD', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='workphone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=-10110, max_length=128),
            preserve_default=False,
        ),
    ]
