# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 21:58
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160904_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personalphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='workphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True),
        ),
    ]
