# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160904_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['addeddate'], 'verbose_name_plural': 'people'},
        ),
        migrations.AddField(
            model_name='person',
            name='employid',
            field=models.CharField(blank=True, max_length=15, verbose_name='Employee number or PRN'),
        ),
        migrations.AddField(
            model_name='person',
            name='tokenserial',
            field=models.CharField(blank=True, max_length=15, verbose_name='Token serial number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='addeddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added to status app'),
        ),
        migrations.AlterField(
            model_name='person',
            name='csctransfer',
            field=models.BooleanField(default=False, verbose_name='Existing CSC employee'),
        ),
        migrations.AlterField(
            model_name='person',
            name='employtype',
            field=models.CharField(choices=[('Contractor', 'Contractor'), ('Employee', 'Employee')], default='Contractor', max_length=50, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='kite',
            field=models.BooleanField(default=False, verbose_name='Assigned to KITE project'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personalemail',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Personal email address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personalphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, verbose_name='Personal phone number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Working remotely'),
        ),
        migrations.AlterField(
            model_name='person',
            name='shortname',
            field=models.CharField(max_length=200, unique=True, verbose_name='CSC shortname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='startdate',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='workphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, verbose_name='Work phone number'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
