# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160904_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
