# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_assignment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personalphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, verbose_name='Personal phone number, format: +1 860 888 6060'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personalstate',
            field=models.CharField(default='CT', max_length=50, verbose_name='Home state (abbreviation)'),
        ),
    ]
